services:  
  server:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
    # volumes:
    #   - .:/app
  mongo :
    image: mongo:6.0.12-jammy
    restart: always
    ports:
      - 27019:27017
 


